name: "Ubuntu Unit Tests"

on: 
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        build_shared: ["OFF", "ON"]
        build_type: [Release, Debug]

    steps:
      - name: ğŸ”¥ Checkout ğŸ”¥
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: ğŸ Setup Python ğŸ
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        
      - name: âš¡ Configure CMake âš¡
        run: |
          python -c "import os;x='${{ matrix.build_type }}';os.environ['IS_BUILD_TYPE_DEBUG']='ON' if x == 'Debug' else 'OFF'"
          cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DMETHAN_BUILD_TEST=ON -DMETHAN_BUILD_SHARED=${{ matrix.build_shared }} -DMETHAN_DEBUG=$IS_BUILD_TYPE_DEBUG
          
      - name: ğŸ”¨ Build ğŸ”¨
        run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.build_type }}

      - name: ğŸ§ª Test ğŸ§ª
        working-directory: ${{ github.workspace }}/build
        run: ctest -C ${{ matrix.build_type }}
