name: "Advanced Testing"

on: [ push ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
        - os: macos-latest
          build_shared: ON
          build_type: Release
        - os: ubuntu-latest
          build_shared: ON
          build_type: Release
        - os: windows-latest
          build_shared: ON
          build_type: Release
        # - os: macos-latest
        #   build_shared: "OFF"
        #   build_type: Release
        # - os: ubuntu-latest
        #   build_shared: "OFF"
        #   build_type: Release
        # - os: windows-latest
        #   build_shared: "OFF"
        #   build_type: Release

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Configure CMake
        run: cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DMETHAN_BUILD_TEST=ON -DMETHAN_BUILD_SHARED=${â€Š{ matrix.build_shared }â€Š} -DMETHAN_DEBUG=ON
      
      - name: ðŸ”¨ Build ðŸ”¨
        run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.build_type }}

      - name: ðŸ§ª Test ðŸ§ª
        working-directory: ${{ github.workspace }}/build
        run: ctest -C ${{ matrix.build_type }}
